// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32            `json:"id"`
	Email         string           `json:"email"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	LastUpdatedAt pgtype.Timestamp `json:"last_updated_at"`
}
